### ISSUE TITLE
/obs players command runnable by anyone

### ISSUE THREAD

**Issue by derg4** [ApacheTech-VintageStory-Mods/Issue-Tracker#1]
In a multiplayer server I was in (1.18.8 stable) which tried out One Bed Sleeping (v2.2.0), I (a regular player) tried out the command and was able to alter the percentage of people needed to sleep, which caused the server to drop the mod immediately. I didn't reproduce it in a sterile environment or anything, just thought I'd drop this here

**Comment by ApacheTech** [comment]
This has now been fixed.
