### ISSUE TITLE
Exception: Unable to load one or more of the requested types. (1.19.3 MP)

### ISSUE THREAD

**Issue by WickedSchnitzel** [ApacheTech-VintageStory-Mods/Issue-Tracker#2]
[Error] [steadycam] Exception: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Vintagestory.Common.ModContainer.GetModSystems(Assembly assembly) in VintagestoryLib\Common\API\ModContainer.cs:line 521
18.2.2024 13:00:21 [Error] [steadycam] Exception: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

No stack trace
18.2.2024 13:00:21 [Error] [steadycam] Exception: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

No stack trace

**Comment by ApacheTech** [comment]
This should now be fixed within v1.3.1
